### PR TITLE
Add Truffleruby head to CI

### PR DESCRIPTION
**Pull request by gogainda**

### CODE REVIEW

**Comment by ashkan18** [comment]
thanks @gogainda for adding this, will merge once the build is passed.

**Comment by ashkan18** [comment]
@gogainda we should keep other ruby versions around. any reason you took them out?

**Comment by gogainda** [comment]
I was just for testing. Travis's become pretty slow recently, will revert those changes. Do you consider moving to Github Actions?

**Comment by ashkan18** [comment]
It's strange that when you only have `truffleruby` it seems to be passing but with multiple versions it fails. right?

RE github actions, I haven't used them but im totally up to try it, is it easy to setup?

**Comment by gogainda** [comment]
yep, looks like some transient issue to me. will fill an issue in truffleruby repo. Regarding the upgrade to Github Actions , it's hard to say if it's hard or not, but in the end CI is faster and more stable for truffleruby builds

**Comment by ashkan18** [comment]
Thanks! and thanks for Github Actions suggestion! I'll give it a try sometime soon, would be fun learning it.

**Comment by gogainda** [comment]
closing in favor https://github.com/ashkan18/graphlient/pull/83

**Pull request closed without merging**
