### PR TITLE
Add 3.2 to the list of Ruby CI versions

### PR DESCRIPTION
**Pull request by igor-drozdov**

### CODE REVIEW

**Comment by dblock** [comment]
Danger failed, the token must have been rotated. Care to pick one from https://github.com/dblock/ruby-enum/blob/master/.github/workflows/danger.yml#L21?

**Comment by igor-drozdov** [comment]
@dblock done 👍

**Comment by dblock** [comment]
Add this to CHANGELOG as "Added support for Ruby 3.2".

**Comment by igor-drozdov** [comment]
@dblock sure, done 👍

**Review by dblock — APPROVED** [review]

**Pull request merged**
