### PR TITLE
Enable fragments

### PR DESCRIPTION
**Pull request by rellampec**
@dblock  I have added some logic to resolve constants defined in a different context, provided that the full namespace path is included on `Graphlient::Query::#parse`, although `stub_const` doesn't seem to offer a way to mock the scenario.

```ruby
module Test
  module Foo
    module Bar
      Fragment = "client.parse ..."
    end
  end
end

module Test
  module Foo
    module Baz
      # use of ___Bar__Fragment
      puts Bar::Fragment
    end
  end
end
```

In the example above, a graphlient.parse in `Baz` referring to `___Bar__Fragment` would fail to resolve. And for this reason, I have added `evaluate` (capture the context) and `resolve_fragment_constant` (constant resolution + type validation).
  * I am using `Graphlient::Errors:Error` for the type validation, but you may see this requires its own error type. so I have not added `spec` to `raise`.

### CODE REVIEW

**Comment by dblock** [comment]
Looks good. Let's increment the version to 0.7.0 per semver part of this PR and update/edit https://github.com/ashkan18/graphlient/blob/master/CHANGELOG.md please?

**Review by ashkan18 — CHANGES_REQUESTED** [review]
Awesome! thanks for doing this! once we add the CHANGELOG entry we can merge and cut a new release!

**Comment by rellampec** [comment]
@ashkan18 added PR changelog and incremented to version `0.7.0`

**Review by ashkan18 — APPROVED** [review]

**Comment by ashkan18** [comment]
Looks like tests are failing, once they are green let's merge 🙌 thanks for doing this ❤️

**Comment by rellampec** [comment]
@ashkan18 I had to change the connection message to pass the tests locally.

image

I have reverted that test to its previous `expect`ed value.

**Comment by ashkan18** [comment]
Awesome! thanks for the quick fix ❤️

**Pull request merged**
